### ISSUE TITLE
v3.4.0 requires IntoParams for actix path parameter types, breaking newtype pattern

### ISSUE THREAD

**Issue by jayvdb** [juhaku/utoipa#675]
On updating to v3.4.0, I get a lot of errors like

```rust
error[E0277]: the trait bound `FooId: IntoParams` is not satisfied
  --> services/blah/src/routes/baz.rs:34:21
   |
34 |     foo_id: Path<FooId>,
   |                     ^^^^^^^^ the trait `IntoParams` is not implemented for `FooId`
```

where `FooId` is a newtype wrapper around uuid. c.f. https://github.com/juhaku/utoipa/discussions/655

Now the fun part is when adding `IntoParams` to `FooId`, I get

```rust
error: struct with unnamed fields must have explicit name declarations.
       
         = help: Try defining `#[into_params(names(...))]` over your type: FooId
       
    --> rust/models/src/lib.rs:2673:16
     |
2673 |     pub struct FooId(pub uuid::Uuid);
     |                ^^^^^^^

```

Note this is code that all worked with v3.3.0.

In the route function definition, I have the name of the single path variable : `foo_id: Path<FooId>` - this approach means the function signature describes the parameter names.

**Comment by juhaku** [comment]
Oh snap, I knew it that when I make the release there will be something that will not work as expected. I'll thy to fix this asap.

**Comment by JohnCMoon** [comment]
Hi, this is impacting my project as well. I've bisected the history and found the issue was introduced by #666 ! 👿 

The error message I'm getting is:
``` 
error[E0277]: the trait bound `ApiVersion: IntoParams` is not satisfied
  --> src/api/core/keywords.rs:86:18
   |
86 |     api_version: ApiVersion,
   |                  ^^^^^^^^^^ the trait `IntoParams` is not implemented for `ApiVersion`
```

I'm using Rocket and my route function looks like this:
```rust
/// Creates a new keyword in the database
#[utoipa::path(
    post,
    path = "/keyword",
    tag = "Keyword",
    request_body = CreateKeywordData,
    responses(
        (status = 201, description = "Keyword created successfully", body = ApiResponse, example = json!(ApiResponse::example_success("created keyword", 201))),
        (status = 409, description = "Keyword already exists", body = ApiResponse, example = json!(ApiResponse::example_failure("keyword already exists", 409))),
        (status = 500, description = "Internal server error", body = ApiResponse, example = json!(ApiResponse::example_500()))
    ),
)]
#[post("/<api_version>/keyword", format = "json", data = "<data>")]
async fn create_keyword(
    api_version: ApiVersion,
    data: Json<CreateKeywordData>,
    conn: DbConn,
) -> StatusResponse {
    match api_version {
        ApiVersion::V1 => _create_keyword(data.0, conn).await,
    }
}
```

In the past, I've set the `api_version` variable as part of the `servers` attribute in the `openapi` macro like this:
```rust
#[derive(OpenApi)]
#[openapi(
    ...
    servers(
        (url = "/api/{api_version}", description = "Keylay API base URL",
            variables(
                ("api_version" = (default = "v1", enum_values("v1"), description = "API version"))
            )
        )
    )
```

This gives me the following near the top of my `openapi.yaml` which is quite nice:
```yaml
servers:
  - url: /api/{api_version}
    description: Keylay API base URL
    variables:
      api_version:
        default: v1
        description: API version
        enum:
          - v1
```

Is there a way to keep this model after the update to automatic query param recognition?

**Comment by juhaku** [comment]
> I've bisected the history and found the issue was introduced by https://github.com/juhaku/utoipa/pull/666 :imp: 

It indeed was quite ominous PR :sweat_smile: 

> I'm using Rocket and my route function looks like this

So you are not defining the parameter within `#[utoipa::path(params(...))]`? 

> Is there a way to keep this model after the update to automatic query param recognition?

Sort of yes, You can always use the explisit values to override auto resolved ones by defining them within `#[utoipa::path()]` macro. However, as for now you need to implement `IntoParams` trait for the `ApiVersion` attribute. The error arises when it tries to add the parameter to the params of the OpenAPI path definition declared with `#[utoipa::path()]` macro. Currently there is no way to "ignore" selected variables of being added. One way to solve this would be to allow variable declaration within `#[utoipa::path(params(...))]` to override parameters. If there is a parameter with same name already defined it would instead use the manual parameter. This would be the opposite on how it now works and needs a change.

**Comment by juhaku** [comment]
@JohnCMoon The new error above is an after effect to the change where before the function arguments were not added to the path parameters whereas now they will be added implicitly. This then expects the parameter to be either primitive type or if the type is a struct or enum it must implement `IntoParams` type. In case of a struct this would be quite simple to just add a `#[derive(IntoParams)]` above the struct. However in the case of enum we need to implement this manually because the enum derive support has not been implemented because it hasn't been considered to be used in such a way.

In your case you can fix the error with the following implementation. You may change it as you see fit.
```rust
#[derive(ToSchema)]
enum ApiVersion {
    V1,
}

impl IntoParams for ApiVersion {
    fn into_params(
        _: impl Fn() -> Option<utoipa::openapi::path::ParameterIn>,
    ) -> Vec<utoipa::openapi::path::Parameter> {
        vec![ParameterBuilder::new()
            .description(Some(""))
            .name("api_version")
            .required(utoipa::openapi::Required::True)
            .parameter_in(utoipa::openapi::path::ParameterIn::Path)
            .schema(Some(schema!(#[inline] ApiVersion)))
            .build()]
    }
}
```

The derive support for enum `IntoParams` could be added in some time in future.

**Comment by rdelfin** [comment]
Thanks for actioning on this so quickly @juhaku! Given this is a breaking change in a minor version, is there any chance this could be made into an impromptu 3.4.1 release and could version 3.4.0 get yanked? Thanks!

**Comment by juhaku** [comment]
Anytime, 

Yeah this is unfortunate breaking change release that should have been 4.0.0. But on the bright side it let us know what is lacking in sense of functionality from the current implementation. You are probably right it's better yank the 3.4.0 until it causes more trouble for more people. I might as well for the next release go the whole nine yards to improve the `IntoParams` implementation. However it not going to change the fact that `IntoParams` must be derived or otherwise implemented for query or path parameters that so require. These are types that are not commonly recognized as primitive types.

**Comment by rdelfin** [comment]
Yeah, absolutely. Honestly I can see an argument for going all in and bumping to 4.0.0 too. Definitely will look into explicitly deriving in our code too though, would have avoided us from hitting this pitfall :sweat_smile:

**Comment by jayvdb** [comment]
@juhaku , your responses here sound like you no longer consider this a bug.  The workaround you gave to my case does not solve my case.

> In the route function definition, I have the name of the single path variable : `foo_id: Path<FooId>` - this approach means the function signature describes the parameter names.

This is valid in actix, and I can do `any_name_I_like: Path<FooId>`.  Your suggestion to use `#[into_params(names("custom_uuid"))]` means that my valid actix functions are no longer supported by utoipa, because in v3.3.0 I could use the same newtype in multiple functions using different arg names - which is quite normal as a newtype is often only a very thin wrapper around a primitive type, or basic type like uuid.  Forcing all newtype to always have the same name in APIs is a very new requirement.  For me, it will mean I need to split many of my newtypes into multiple types so this new "one newtype = one API name" constraint can be satisfied.  This isnt the end of the world, but deserves fixing or yanking 3.4.0.  I'd prefer it was fixed, because I'd prefer utoipa doesnt reject valid actix code, but I'll adjust our codebase if this subset of actix is no longer acceptable.

**Comment by juhaku** [comment]
@jayvdb This is a good argument and I prefer to keep the code as flexible as possible without restricting the syntax. But that also makes the auto generation difficult because there multiple ways to accomplish something and all of them should be covered. 

> This is valid in actix, and I can do `any_name_I_like: Path<FooId>`. Your suggestion to use `#[into_params(names("custom_uuid"))]`

To be honest, I am not sure whether it actually enforces the `names(...)` to match, but it surely enforces users to define the `names` attribute.  :laughing:  I could make the names attribute optional (I think so). :thinking:  I could also make sure that the name is taken from the actix handler argument name like discussed ( `any_name_I_like: Path<FooId>`). However I prior actix_web 3.0.0 syntax like this was allowed:  `Path((id, name)): Path<(i32, String)>` but since then the left hand side of argument cannot be destructed. This disallows "naming" tuple style path parameters in actix_web. Luckily the `Path` can get the parameters from the `#[get("...")]` macro but `Query` at the other hand does not. Though I don't know is something like `Query<(i32, String)>` a valid use case. Moreover how this kind of parameter should be interpreted? Should it be interpreted as array of 2 elements, one int, another string like serde would interpret and serialize the tuple? Or should they be interpreted as separate arguments? In `Path` these are separate arguments, but in `Query` we cannot resolve the names for them if they were separate arguments.

I'd consider this as an incomplete feature what manifests as an error above. It's not a programming error, it never was fully implemented. :laughing: The symptoms didn't surface because the parameters mostly was inputted manually. But it is a bug in sense of "something or in this case functionality that is expected to work does not work".

My plan is to fix this implementation according to:

* `IntoParams` can be derived from structs, and enums (currently only structs are allowed).
* `IntoParams` would not require the `names(...)` attribute but can be provided. Or if I see that it is completely unnecessary, it may be removed as well. Any thoughts on this?
* Name for the parameter would firstly taken from the name of the operation handler argument but with exception on path parameters, these will take the name from the macro path.
* Parameters would work correctly with the `Option<T>`. Currently this is working only in certain cases which is not enough to cover the relevant cases and it seems like there is currently bug which occurs only when `actix_extras` or `axum_extras`, `rocket_extras` is enabled. 

Is there anything else `IntoParams` should take into account?

**Comment by juhaku** [comment]
Related #687

**Comment by JohnCMoon** [comment]
@juhaku, thanks for the quick support here. Indeed implementing `IntoParams` in my use case does solve the build issue, but the output `openapi.yaml` isn't as desirable as before.

Looking at [this OpenAPI document](https://catalog.redhat.com/api/containers/v1/ui/) as an example, you can see they have the API version, `v1`, defined as part of the base server URL and then the API endpoints tack on to that. I'm trying to do something similar.

With utoipa automatically adding all params in the route, all the endpoints in my document all get a new `api_version` param added:

```
   /keyword/{keyword}:
     get:
       tags:
         - Keyword
       summary: Get keyword details
       description: Get keyword details
       operationId: get_keyword
       parameters:
         - name: keyword
           in: path
           description: Keyword to search for
           required: true
           schema:
             type: string
+        - name: api_version
+          in: path
+          description: ""
+          required: true
+          schema:
+            type: string
+            enum:
+              - V1
       responses:
```

Would it be possible to say "this param is part of the base URL and should not be used in the endpoint doc"? The auto-generated params feature cause this digression, but this issue is slightly off-topic so LMK if I should make a separate issue to continue discussion. :)

**Comment by juhaku** [comment]
> ...generated params feature cause this digression, but this issue is slightly off-topic so LMK if I should make a separate issue to continue discussion. :)

I think the discussion can continue on this thread.

```rust
/// Creates a new keyword in the database
#[utoipa::path(
    post,
    path = "/keyword",
    tag = "Keyword",
    request_body = CreateKeywordData,
    responses(
        (status = 201, description = "Keyword created successfully", body = ApiResponse, example = json!(ApiResponse::example_success("created keyword", 201))),
        (status = 409, description = "Keyword already exists", body = ApiResponse, example = json!(ApiResponse::example_failure("keyword already exists", 409))),
        (status = 500, description = "Internal server error", body = ApiResponse, example = json!(ApiResponse::example_500()))
    ),
)]
#[post("/<api_version>/keyword", format = "json", data = "<data>")]
async fn create_keyword(
    api_version: ApiVersion,
    data: Json<CreateKeywordData>,
    conn: DbConn,
) -> StatusResponse {
    match api_version {
        ApiVersion::V1 => _create_keyword(data.0, conn).await,
    }
}
```
> Would it be possible to say "this param is part of the base URL and should not be used in the endpoint doc"?

With rocket route like one above to exclude parameter from being automatically added, the parameter should not be listed within the `#[post("/<api_version>/keyword", format = "json", data = "<data>")]` macro. E.g if we want to exclude the `api_version` from the parameters then the macro should look more like this `#[post("/keyword", format = "json", data = "<data>")]`. This is because we cannot add macro attributes for function arguments e.g. this is not possible.
```rust
#[post("/<api_version>/keyword", format = "json", data = "<data>")]
async fn create_keyword(
    #[path_ignore_yeah] api_version: ApiVersion,
    data: Json<CreateKeywordData>,
    conn: DbConn,
) -> StatusResponse {
    match api_version {
        ApiVersion::V1 => _create_keyword(data.0, conn).await,
    }
}
```

Furthermore just based on function argument `api_version: ApiVersion` we cannot know whether the argument should be ignored or not nor we can determine how it should be handled. Only way to make a connection between function arguments and path and query parameters is to define the name for the arguments in macro and match it to the function argument name.

**Comment by juhaku** [comment]
The old behavior for path and query parameters is restored here #696 to allow furhter releases from the master branch. The improved `IntoParams` needs furhter planning and experiementing before it can be fully implemented which might take some time. With this I am going to make a release 3.4.1 with the changes soon.
