### ISSUE TITLE
Error after update from 5.2.0 to 5.3.0

### ISSUE THREAD

**Issue by artemiokost** [juhaku/utoipa#1265]
```
error: expected expression, found `let` statement
  --> api/src/config/swagger.rs:54:9
   |
54 |         dto::page::Response<dto::get::unit::Response>,
   |         ^^^
   |
   = note: only supported directly in conditions of `if` and `while` expressions
   
error[E0061]: this method takes 2 arguments but 3 arguments were supplied
   --> api/src/config/swagger.rs:13:10
    |
13  | #[derive(OpenApi)]
    |          ^^^^^^^
...
54  |         dto::page::Response<dto::get::unit::Response>,
    |         --- unexpected argument #3
    |
note: method defined here
   --> /Users/artemiokost/.cargo/registry/src/index.crates.io-6f17d22bba15001f/utoipa-5.3.0/src/openapi/schema.rs:136:12
    |
136 |     pub fn schema<S: Into<String>, I: Into<RefOr<Schema>>>(mut self, name: S, schema: I) -> Self {
    |            ^^^^^^
    = note: this error originates in the derive macro `OpenApi` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Error occurs when I'm using generic type
```
   components(schemas(
        dto::page::Response<dto::get::unit::Response>,
        dto::page::Response<dto::get::user::Response>,
    ))
```
    
Previously it was ok

**Comment by juhaku** [comment]
You could try to `cargo update`

**Comment by artemiokost** [comment]
@juhaku Yeah I have try
More info:

```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
#[schema(as = dto::page::Response)]
#[serde(rename_all = "camelCase")]
pub struct Response<T: Serialize + ToSchema> {
    pub list: Vec<T>,
    pub num: u64,
    pub size: u64,
    pub total: u64,
}
```
```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, ToSchema)]
#[schema(as = dto::get::unit::Response)]
#[serde(rename_all = "camelCase")]
pub struct Response {
    pub id: i64,
    #[schema(value_type = String)]
    pub created_at: NaiveDateTime,
    #[schema(value_type = String)]
    pub updated_at: NaiveDateTime,
    pub latitude: f64,
    pub longitude: f64,
    #[schema(value_type = entity::currency::Symbol)]
    pub currency: entity::currency::Symbol,
    #[schema(value_type = String)]
    pub price: Decimal,
    pub title: String,
    pub description: Option<String>,
    pub country: String,
    pub region: Option<String>,
    pub city: String,
    pub address: String,
    #[schema(value_type = entity::unit::Status)]
    pub status: Status,
    #[schema(value_type = get::user::Response)]
    pub creator: get::user::Response,
    #[schema(value_type = Vec<entity::media::Model>)]
    pub media_list: Vec<entity::media::Model>,
}
```

**Comment by juhaku** [comment]
Oh man, something has changed, and this is a bug in recent changes, it currently generates incorrect code in this case :disappointed: I'll try to resolve this as next thing.
