### ISSUE TITLE
Conflicting implementations of `utoipa::ParameterIn`

### ISSUE THREAD

**Issue by 1lutz** [juhaku/utoipa#132]
This code used to compile in version "0.1.2":

```rust
#[derive(Serialize, Deserialize, Component)]
struct WorkflowId(u64);

#[utoipa::path(get, path = "/workflow/{id}")]
async fn load_workflow(id: Path<WorkflowId>) {}

#[utoipa::path(delete, path = "/workflow/{id}")]
async fn delete_workflow(id: Path<WorkflowId>) {}
```

In the current version "1.0.2" the compilers yields

```
error[E0119]: conflicting implementations of trait `utoipa::ParameterIn` for type `WorkflowId`
  --> src/main.rs:12:35
   |
9  | async fn load_workflow(id: Path<WorkflowId>) {}
   |                                 ---------- first implementation here
...
12 | async fn delete_workflow(id: Path<WorkflowId>) {}
   |                                   ^^^^^^^^^^ conflicting implementation for `WorkflowId`
```

**Comment by juhaku** [comment]
This is indeed is unwanted behaviour caused by the new IntoParams functionality for actix-web. Thanks for noticing, I'll try to solve this one for the next release. But currently there is no cure for this, other than what comes to above code could also be written using type alias giving you same behaviour if there is no need to add any other custom logic to the workflow id with via implementing traits etc.
>```rust
>type WorkflowId = u64;
>
>#[utoipa::path(get, path = "/workflow/{id}")]
>async fn load_workflow(id: Path<WorkflowId>) {}
>
>#[utoipa::path(delete, path = "/workflow/{id}")]
>async fn delete_workflow(id: Path<WorkflowId>) {}
>```

**Comment by supercmmetry** [comment]
Hi @juhaku, I'm having the same problem with query in actix. Using aliases doesn't seem to help.

**Comment by supercmmetry** [comment]
Maybe instead of creating impls for the struct itself we could do something like this

```rust

impl ParameterIn for WorkflowId_load_workflow {

}

impl ParameterIn for WorkflowId_delete_workflow {

}
```

**Comment by juhaku** [comment]
@supercmmetry  @1lutz 

> Maybe instead of creating impls for the struct itself we could do something like this
> 
> ```rust
> impl ParameterIn for WorkflowId_load_workflow {
> 
> }
> 
> impl ParameterIn for WorkflowId_delete_workflow {
> 
> }
> ```
> 
> Or, we could use monads instead to specify if the struct is part of a query/header/etc
> 
> Something like this:
> 
> ```rust
> type WorkflowId = u64;
> 
> #[utoipa::path(get, path = "/workflow/{id}")]
> async fn load_workflow(id: Query<utoipa::Query<WorkflowId>>) {}
> 
> #[utoipa::path(delete, path = "/workflow/{id}")]
> async fn delete_workflow(id: Path<utoipa::Path<WorkflowId>>) {}
> ```
> 
> Here the monads: utoipa::Query and utoipa::Path would wrap structs and impl ParameterIn appropriately for them.

Yes, actually why not. There is a sides for each an every of those implementations. For the first one it is most transparent to the end users. However will create unnecessary duplicate code but that is not too big of an issue. And it is propably the simpliest implementation though.

The second is nice. I also considered someting like this since it would then provide nicely support for other frameworks as well. However not sure how willing peeps are to use the extra wrapper type for those. 

Third option that I was thinking regarding this is to completely get rid of the `ParameterIn` trait that I introduced there but that is also a bit of a working progress. It might be that I need to implement the monads for other frameworks eventually though.

My current idea is to finish the enhanced generics first #108 and then tackle this one. The generics are half done so it only needs final squeeze when I just find time.

PS. sorry for late reply been really busy these days making me not too responsive.

**Comment by juhaku** [comment]
Fix for this has been released now here one can find docs relating to this feature https://docs.rs/utoipa/1.1.0/utoipa/derive.IntoParams.html#intoparams-attributes-for-into_params.  

Here is modified example of one posted previously which now should work. **Note** there is now `#[into_params]` attribute added the the type which is used to give name for unnamed type in OpenAPI schema.
```rust
#[derive(Serialize, Deserialize, IntoParams)]
#[into_params(names("id"))]
struct WorkflowId(u64);

#[utoipa::path(get, path = "/workflow/{id}")]
async fn load_workflow(id: Path<WorkflowId>) {}

#[utoipa::path(delete, path = "/workflow/{id}")]
async fn delete_workflow(id: Path<WorkflowId>) {}
```
